config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :members
  resources :event_attendance do
    collection do
      post 'remove'
    end
  end
  root :to => redirect('/events/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_attendances
  has_many :members, through: :event_attendances
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :member
  belongs_to :event
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :event_attendances
  has_many :events, through: :event_attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_attendance_controller.rb
class EventAttendanceController < ApplicationController
  def index
  
  end
  
  def new

  end
  
  def edit
    @event = Event.find(params[:id])
    @present = @event.members.map{ |u| [ u.name, u.id ] }
    @presentID = @event.members.map(&:id)
    @absent = Member.where.not(id: @presentID).map{ |u| [ u.name, u.id ] }
    respond_to do |format|
      format.js
    end
  end
    
  def create
    @event = Event.find(params[:event_attendance][:event])
    params[:event_attendance][:absent].each do |p|
      if p != ""
        @member = Member.find(p)
        @event.members << @member
      end
    end
    redirect_to "/events/" + @event.id.to_s
  end
  
  def remove
    @event = Event.find(params[:event_attendance][:event])
    params[:event_attendance][:present].each do |p|
      if p != ""
        @member = Member.find(p)
        @event.members.delete(@member)
      end
    end
    redirect_to "/events/" + @event.id.to_s
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end
  
  def index
    redirect_to "/events/" + Event.last.id.to_s
  end
  
  def show
    @event = Event.find(params[:id])
	respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def edit
    @event = Event.find(params[:id])
	@events = Event.all
	respond_to do |format|
      format.js
    end
  end
  
  def create
    @event = Event.new(eventNew_params)
    @event.save
	redirect_to "/events/" + @event.id.to_s
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to "/events/" + @event.id.to_s
    else
      render 'edit'
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to "/events/"
  end
  
 private
    def eventNew_params
      params.require(:eventNew).permit(:name, :start_time, :end_time, :venue)
    end
    def event_params
      params.require(:event).permit(:name, :start_time, :end_time, :venue)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end
  
  def create
    @member = Member.new(member_params)
    @member.save
	
	@members = Member.all
    redirect_to "/members/"
  end
  
  def edit
    @member = Member.find(params[:id])
	@id = params[:id]
	respond_to do |format|
      format.js
    end
  end 
  
  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to "/members/"
    else
      render 'edit'
    end
  end
  
  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to "/members/"
  end
  
  
 private
    def member_params
      params.require(:member).permit(:name, :serial_no)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendance_helper.rb
module EventAttendanceHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/event_attendance/_edit.html.erb
<%-#= form_for :event_attendance, :id => 'create-form', url: {action: "create"}, remote: true do |f| -%>
<%= form_for :event_attendance, :id => 'create-form', url: {action: "create"} do |f| %>
    <%= f.hidden_field :event, :value => @event.id %>
    <%= f.select(:absent, @absent,{ :prompt => "Absent"}, { :multiple => true, :size => 10}) %>
    <div id="create-status"></div>
    <br>
    <%= f.submit "Add" %> 
<% end %>

<%-#f= orm_for :event_attendance, :id => 'remove-form', url: {action: "remove"}, remote: true do |f2| -%>
<%= form_for :event_attendance, :id => 'remove-form', url: {action: "remove"} do |f2| %>
    <%= f2.hidden_field :event, :value => @event.id %>
    <%= f2.submit "Remove" %>
    <br>
    <%= f2.select(:present, @present,{ :prompt => "Present"}, { :multiple => true, :size => 10}) %>
    <div id="remove-status"></div>
<% end %>

<script type="text/javascript">
/*$("#create-form").submit(function() 
{  
    $("#create-status").html("saving");
    var valuesToSubmit = $(this).serialize();
    $.ajax({
        type: "POST",
        url: $(this).attr("create"), 
        data: valuesToSubmit,
        dataType: "JSON" 
    });
    return false;
});*/
</script>

app/views/event_attendance/edit.js.erb
$("#attendance").html('<%= escape_javascript(render 'edit') %>');

app/views/events/_edit.html.erb
<%= select("events", "name", Event.order('id DESC').all.collect {|p| [ p.name, p.id ] }, { include_blank: false, :selected => @event.id }) %>
<%= form_for :event, url: event_path(@event),  method: :patch do |f| %>
<p>
    <%= f.label :name, 'Event Name:' %>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.label :start_time, 'Start Time:' %>
    <%= f.datetime_local_field :start_time %>
</p>
<p>
    <%= f.label :end_time, 'End Time:' %>
    <%= f.datetime_local_field :end_time %>
</p>
<p>
    <%= f.label :venue, 'Venue:' %>
    <%= f.text_field :venue %>
</p>
<%= f.submit 'Update Event' %>  <%= link_to 'Remove Event', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/events/_new.html.erb
<a href="javascript:void(0);" id="create-new">Create New</a>
<div id="new-hidden" style="display:none;">
<h2>New Event</h2>
<%= form_for :eventNew, :id => 'new-form', url: events_path do |f|%>
    <p>
        <%= f.label :name, 'Event Name:' %>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :start_time, 'Start Time:' %>
        <%= f.datetime_local_field :start_time %>
    </p>
    <p>
        <%= f.label :end_time, 'End Time:', class: "datetime-local" %>
        <%= f.datetime_local_field :end_time %>
    </p>
    <p>
        <%= f.label :venue, 'Venue:' %>
        <%= f.text_field :venue %>
    </p>
    <%= f.submit 'Save Event' %>
    <a href="javascript:void(0);" id="cancel-new">Cancel</a>
    <div id="new-status">Unsaved</div>
<% end %>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $("#create-new").click(function () 
        {
            $("#new-hidden").css("display", "block");
            $("#eventNew_name").focus();
        });
    $("#cancel-new").click(function () 
    {
        $("#new-hidden").css("display", "none");
    });
});

$("#new-form").submit(function() 
{  
    $("#new-status").html("saving");
    var valuesToSubmit = $(this).serialize();
    $.ajax({
        type: "POST",
        url: $(this).attr("create"), 
        data: valuesToSubmit,
        dataType: "JSON" 
    });
    return false;
});
</script>

app/views/events/edit.js.erb
$("#edit").html('<%= escape_javascript(render 'edit') %>');

app/views/events/index.html.erb
<p>index.html.erb</p>

app/views/events/show.html.erb
<script type="text/javascript">
  $(function (){
     $(document).on("change","#events_name", function (){
        window.history.pushState("", "", + this.value);
        $.ajax({ url: this.value + "/edit" });
        $.ajax({ url: "../event_attendance/" + this.value + "/edit" }); 
     });
     $(document).ready(function (){
        var id = <%= @event.id %>;
        $.ajax({ url: id + "/edit" });
        $.ajax({ url: "../event_attendance/" + id + "/edit" });
     });
  });
</script>

<div class="main">
    <h1>Events</h1>
    <div id="new"><%= render "new" %></div>
    <div id="edit"></div>
    <hr>
    <div id="attendance"></div>
</div>

app/views/layouts/_footer.html.erb
<div class="header">
    <div class="container">
        <span class="footer">This is footer.</span>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
    <ul>
        <li><a href="/events/">Home</a></li>
        <li><a href="/events/">Event</a></li>
        <li><a href="/members/">Member</a></li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8" />
    <title>Attendance System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <hr/>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/members/_edit.html.erb
<%= form_for :member, url: member_path(@member),  method: :patch do |f| %>
<p>
    <%= f.label :name, 'Member Name:' %>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.label :serial_no, 'Serial No:' %>
    <%= f.text_field :serial_no %>
</p>
<%= f.submit 'Update Member' %> <%= link_to 'Remove Member', member_path(@member), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


app/views/members/_new.html.erb
<h2>New Member</h2>
<%= form_for :member, url: members_path do |f| %>
    <p>
        <%= f.label :name, 'Member Name:' %>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :serial_no, 'Serial No:' %>
        <%= f.text_field :serial_no %>
    </p>
    <%= f.submit 'Save Member' %>
    <a href="javascript:void(0);" id="cancel-new">Cancel</a>
<% end %>

<script type="text/javascript">
    $(document).ready(function() {
        $("#cancel-new").click(function () 
        {
            $("#new-member").html("");
        });
    });
</script>

app/views/members/edit.js.erb
$("#member-details-<%= @id %>").html('<%= escape_javascript(render 'edit') %>');

app/views/members/index.html.erb
<script type="text/javascript">
  $(function (){
     $(document).on("click",".member-name", function (){
        var id = $(this).attr("value");
        if ($("#member-details-" + id).css("display") == "none")
        {
            $("#member-details-" + id).css("display", "block");
            $.ajax({ url:  id + "/edit" });
        }
        else
        {
            $("#member-details-" + id).css("display", "none");
        }
     });

  });   
</script>

<div class="main">
    <h1>Members</h1>
    <%= link_to "Create New", 'new', :remote => true %>
    <div id="new-member"></div>

    <div id="member-list">
        <ul>
            <div id="<%= "edit-details" %>"></div>
            <% @members.each do |member| %>
                <li><%= link_to member.name, edit_member_path(member), :class => "member-name", :value => member.id, :remote => true %></li>
                <div style="display:none;" id="member-details-<%= member.id %>"></div>
            <% end %>
        </ul>
        
    </div>
</div>

app/views/members/new.js.erb
$("#new-member").html('<%= escape_javascript(render 'new') %>');
$("#member_name").focus();